# Generated by Django 5.2.1 on 2025-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='link_to_apply',
            field=models.URLField(max_length=1000),
        ),
    ]
